import type { QuizQuestion } from "../types";

// Sourced from Task Sheet 2.1-5 "Installing Network Cables" and Job Sheet 2.2-2 "Setting-Up
// Network Configuration" (see /modules/uc 2), plus the UC 2 Guide's step-by-step Windows
// networking walkthrough. Each task gets its own 15-question quiz, keyed by taskId.

const task1Quiz: QuizQuestion[] = [
  {
    id: "m2t1-q1",
    type: "multiple_choice",
    prompt: "What standard governs how structured network cabling should be created, per Task Sheet 2.1-5?",
    options: [
      { id: "a", text: "The cabling standards set by ANSI/TIA/EIA" },
      { id: "b", text: "There is no standard -- any wiring order works" },
      { id: "c", text: "The manufacturer of the RJ45 connector only" },
      { id: "d", text: "ISO 9001" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet requires cable to be created \"following the cabling standards set by ANSI/TIA/EIA.\"",
  },
  {
    id: "m2t1-q2",
    type: "multiple_choice",
    prompt: "In the T568B wiring standard, which pair sits in pins 1 and 2?",
    options: [
      { id: "a", text: "White-orange, then orange" },
      { id: "b", text: "White-green, then green" },
      { id: "c", text: "White-blue, then blue" },
      { id: "d", text: "White-brown, then brown" },
    ],
    correctOptionIds: ["a"],
    explanation: "T568B's pin order is: white-orange, orange, white-green, blue, white-blue, green, white-brown, brown.",
  },
  {
    id: "m2t1-q3",
    type: "true_false",
    prompt: "Wiring both ends of a cable to the same standard (e.g. T568B on both ends) produces a straight-through cable.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "A straight-through cable uses the same standard on both ends; wiring one end T568A and the other T568B produces a crossover cable instead.",
  },
  {
    id: "m2t1-q4",
    type: "multiple_choice",
    prompt: "What is a crimping tool used for in this task?",
    options: [
      { id: "a", text: "Attaching (crimping) an RJ45 connector onto the end of a UTP cable" },
      { id: "b", text: "Testing whether a cable works" },
      { id: "c", text: "Stripping the cable's outer jacket" },
      { id: "d", text: "Punching a wire down onto a keystone jack" },
    ],
    correctOptionIds: ["a"],
    explanation: "Crimping tools press the RJ45 connector's pins down through the individual wires to make the electrical connection.",
  },
  {
    id: "m2t1-q5",
    type: "multiple_choice",
    prompt: "What does a LAN cable tester check for?",
    options: [
      { id: "a", text: "Whether each wire is correctly connected end-to-end, with no wiring faults" },
      { id: "b", text: "The cable's exact physical length" },
      { id: "c", text: "The Wi-Fi signal strength" },
      { id: "d", text: "The color of the cable jacket" },
    ],
    correctOptionIds: ["a"],
    explanation: "A LAN tester lights up each pin/pair to confirm continuity and correct wiring order, catching a bad crimp before it's relied on.",
  },
  {
    id: "m2t1-q6",
    type: "multiple_choice",
    prompt: "What's the purpose of a punch-down tool, listed among this task's tools?",
    options: [
      { id: "a", text: "Terminating individual wires onto a keystone jack or patch panel" },
      { id: "b", text: "Crimping an RJ45 connector" },
      { id: "c", text: "Testing a completed cable" },
      { id: "d", text: "Cutting the cable to length" },
    ],
    correctOptionIds: ["a"],
    explanation: "A punch-down tool seats a wire into a jack or patch panel's insulation-displacement contacts, an alternative termination to a crimped RJ45 plug.",
  },
  {
    id: "m2t1-q7",
    type: "multiple_choice",
    prompt: "What's a wire stripper used for when preparing a network cable?",
    options: [
      { id: "a", text: "Removing the outer jacket to expose the individual wire pairs" },
      { id: "b", text: "Testing signal strength" },
      { id: "c", text: "Attaching the connector" },
      { id: "d", text: "Labeling the cable" },
    ],
    correctOptionIds: ["a"],
    explanation: "Before the pairs can be arranged and crimped, the outer jacket has to be stripped back to expose them.",
  },
  {
    id: "m2t1-q8",
    type: "true_false",
    prompt: "Cat6 cable generally supports higher data transmission performance than Cat5e.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "Cat6 has tighter twist rates and better shielding against crosstalk, giving it higher bandwidth and better performance at longer distances than Cat5e.",
  },
  {
    id: "m2t1-q9",
    type: "multiple_choice",
    prompt: "What's the first step of this task, before any cable is even cut?",
    options: [
      { id: "a", text: "Create a network diagram and plan the cable routes" },
      { id: "b", text: "Crimp the RJ45 connector" },
      { id: "c", text: "Test the cable" },
      { id: "d", text: "Punch down the wires" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 2.1-5 has the technician plan the diagram and cable routes before creating and installing any cable.",
  },
  {
    id: "m2t1-q10",
    type: "multiple_choice",
    prompt: "How many pins does a standard RJ45 connector have?",
    options: [
      { id: "a", text: "8" },
      { id: "b", text: "4" },
      { id: "c", text: "6" },
      { id: "d", text: "10" },
    ],
    correctOptionIds: ["a"],
    explanation: "RJ45 is an 8P8C connector -- 8 positions, all 8 wired -- matching a UTP cable's 4 twisted pairs.",
  },
  {
    id: "m2t1-q11",
    type: "multiple_choice",
    prompt: "What can happen if a cable isn't tested with a LAN tester before being relied on?",
    options: [
      { id: "a", text: "A miswired or damaged cable could cause intermittent or total connection failure later" },
      { id: "b", text: "Nothing -- testing is purely cosmetic" },
      { id: "c", text: "The cable becomes permanently unusable" },
      { id: "d", text: "It voids the RJ45 connector's warranty" },
    ],
    correctOptionIds: ["a"],
    explanation: "An untested cable might look fine but have a wiring fault that only shows up as unreliable or dead connectivity once deployed.",
  },
  {
    id: "m2t1-q12",
    type: "image_identification",
    prompt: "This is the UTP patch cable you're terminating in this task. Which pair of tools does the task actually require to finish it?",
    model3d: { url: "/models/cable.glb", rotation: [0, 0, Math.PI / 2.2] },
    options: [
      { id: "a", text: "A crimping tool to attach the connector, then a LAN cable tester to verify it" },
      { id: "b", text: "A soldering iron only" },
      { id: "c", text: "A screwdriver only" },
      { id: "d", text: "No tools are required" },
    ],
    correctOptionIds: ["a"],
    explanation: "The cable is terminated with a crimping tool, then verified with a LAN tester -- both are named in the task sheet's tools list.",
  },
  {
    id: "m2t1-q13",
    type: "multiple_choice",
    prompt: "Good cable-route planning tries to avoid running network cable close to what kind of source?",
    options: [
      { id: "a", text: "Sources of electromagnetic interference, like power lines or fluorescent ballasts" },
      { id: "b", text: "Other network cables of the same type" },
      { id: "c", text: "Water-based fire extinguishers" },
      { id: "d", text: "Wi-Fi routers only" },
    ],
    correctOptionIds: ["a"],
    explanation: "EMI sources near a run of UTP cable can induce noise on the pairs and degrade signal quality.",
  },
  {
    id: "m2t1-q14",
    type: "multiple_choice",
    prompt: "Why does this task sheet require following ANSI/TIA/EIA cabling standards rather than any wiring order that happens to work?",
    options: [
      { id: "a", text: "Standardized, consistent wiring keeps cabling reliable and interoperable across a whole installation" },
      { id: "b", text: "It makes the cable a different color" },
      { id: "c", text: "It's only a legal formality with no technical benefit" },
      { id: "d", text: "Non-standard wiring is always faster" },
    ],
    correctOptionIds: ["a"],
    explanation: "Structured cabling standards exist so cable made by different people, at different times, still works together predictably.",
  },
  {
    id: "m2t1-q15",
    type: "multiple_choice",
    prompt: "What's the assessment method used for this task, per the task sheet?",
    options: [
      { id: "a", text: "Demonstration with oral questioning and a performance criteria checklist" },
      { id: "b", text: "A closed-book exam only" },
      { id: "c", text: "No assessment is specified" },
      { id: "d", text: "Group project submission" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 2.1-5 is assessed via demonstration with oral questioning, scored against a performance criteria checklist.",
  },
];

const task2Quiz: QuizQuestion[] = [
  {
    id: "m2t2-q1",
    type: "multiple_choice",
    prompt: "What should NIC (network interface card) settings be configured to match?",
    options: [
      { id: "a", text: "The network design" },
      { id: "b", text: "The computer's case color" },
      { id: "c", text: "The RAM's manufacturer" },
      { id: "d", text: "Nothing -- default settings always work" },
    ],
    correctOptionIds: ["a"],
    explanation: "Job Sheet 2.2-2 has the technician configure NIC settings \"based on the network design.\"",
  },
  {
    id: "m2t2-q2",
    type: "multiple_choice",
    prompt: "What's the difference between a static and a dynamic peer-to-peer IP configuration?",
    options: [
      { id: "a", text: "Static uses a manually assigned address; dynamic gets its address automatically (e.g. via DHCP)" },
      { id: "b", text: "They're two names for the exact same configuration" },
      { id: "c", text: "Static only works over Wi-Fi" },
      { id: "d", text: "Dynamic requires a physical cable while static doesn't" },
    ],
    correctOptionIds: ["a"],
    explanation: "Job Sheet 2.2-2 has the learner perform both: peer-to-peer using static IP addressing, then again using dynamic IP addressing.",
  },
  {
    id: "m2t2-q3",
    type: "multiple_choice",
    prompt: "When configuring the router, what two things does the task sheet specifically say to change from their defaults?",
    options: [
      { id: "a", text: "The SSID (network name) and the password" },
      { id: "b", text: "The physical color of the router casing" },
      { id: "c", text: "The brand name of the router" },
      { id: "d", text: "Nothing needs to be changed from default" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's step is explicit: \"rename your SSID and provide it with a password of your choice.\"",
  },
  {
    id: "m2t2-q4",
    type: "multiple_choice",
    prompt: "What does a default gateway do on a home or office network?",
    options: [
      { id: "a", text: "Routes traffic between the local network and other networks, like the internet" },
      { id: "b", text: "Assigns a static color scheme to network drives" },
      { id: "c", text: "Only stores backup files" },
      { id: "d", text: "Blocks all outbound traffic permanently" },
    ],
    correctOptionIds: ["a"],
    explanation: "The default gateway (typically the router) is the exit point local devices send non-local traffic through.",
  },
  {
    id: "m2t2-q5",
    type: "multiple_choice",
    prompt: "In the UC 2 Guide's walkthrough, what command is typed into cmd to view a computer's current IP configuration?",
    options: [
      { id: "a", text: "ipconfig" },
      { id: "b", text: "netstat" },
      { id: "c", text: "format" },
      { id: "d", text: "chkdsk" },
    ],
    correctOptionIds: ["a"],
    explanation: "The guide has the learner open cmd and type ipconfig, then read off the default gateway's IP from the result.",
  },
  {
    id: "m2t2-q6",
    type: "multiple_choice",
    prompt: "What's the role of the firewall/security settings this task has you manage?",
    options: [
      { id: "a", text: "Controlling what network traffic is allowed to or from the computer" },
      { id: "b", text: "Speeding up file transfers" },
      { id: "c", text: "Changing the desktop wallpaper" },
      { id: "d", text: "Assigning IP addresses" },
    ],
    correctOptionIds: ["a"],
    explanation: "Firewall settings are managed \"in accordance with manufacturers' instructions and end-user preferences\" to control network access.",
  },
  {
    id: "m2t2-q7",
    type: "multiple_choice",
    prompt: "After creating and sharing a folder on every connected PC, what does the task sheet require you to confirm?",
    options: [
      { id: "a", text: "That everyone connected to the network is able to access the shared folder" },
      { id: "b", text: "That the folder is password-protected with a unique password per user" },
      { id: "c", text: "That the folder is deleted afterward" },
      { id: "d", text: "Nothing further needs confirming" },
    ],
    correctOptionIds: ["a"],
    explanation: "The step reads: \"Make sure that everyone connected to the network is able to access the shared folder.\"",
  },
  {
    id: "m2t2-q8",
    type: "true_false",
    prompt: "This task's steps include disabling / turning off password-protected sharing.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "\"Disable / turn off password protected sharing\" is one of Job Sheet 2.2-2's explicit steps, simplifying access on the trusted local network.",
  },
  {
    id: "m2t2-q9",
    type: "multiple_choice",
    prompt: "How can a technician confirm that every computer connected to the network is actually visible on it?",
    options: [
      { id: "a", text: "Check the Network view in File Explorer (or open This PC) to see if the other computers appear" },
      { id: "b", text: "Unplug the router" },
      { id: "c", text: "Restart every computer" },
      { id: "d", text: "There's no way to check this" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet's checklist item is \"Check if all the computers connected to the network is seen,\" verified through Windows' network view.",
  },
  {
    id: "m2t2-q10",
    type: "multiple_choice",
    prompt: "What's the last step listed in Job Sheet 2.2-2's procedure?",
    options: [
      { id: "a", text: "Diagnose and check any fault or problem in the network system" },
      { id: "b", text: "Configure the NIC" },
      { id: "c", text: "Create a shared folder" },
      { id: "d", text: "Rename the SSID" },
    ],
    correctOptionIds: ["a"],
    explanation: "The procedure ends with diagnosing and checking for any fault or problem in the network system.",
  },
  {
    id: "m2t2-q11",
    type: "multiple_choice",
    prompt: "Which command's output shows every adapter's IPv4 address, subnet mask, and default gateway at once -- useful for diagnosing a network fault?",
    options: [
      { id: "a", text: "ipconfig /all" },
      { id: "b", text: "del *.*" },
      { id: "c", text: "defrag" },
      { id: "d", text: "sfc /scannow" },
    ],
    correctOptionIds: ["a"],
    explanation: "ipconfig /all lists every network adapter's full configuration in one place, which is exactly what's needed to spot a misconfigured address, mask, or gateway.",
  },
  {
    id: "m2t2-q12",
    type: "image_identification",
    prompt: "This is the router you configured for this task. Besides Wi-Fi access, what two network services does it typically provide to a small LAN?",
    model3d: { url: "/models/router.glb" },
    options: [
      { id: "a", text: "DHCP (automatic IP assignment) and acting as the default gateway to other networks" },
      { id: "b", text: "Antivirus scanning and disk defragmentation" },
      { id: "c", text: "Printer driver installation only" },
      { id: "d", text: "Nothing beyond Wi-Fi broadcasting" },
    ],
    correctOptionIds: ["a"],
    explanation: "A home/office router typically combines DHCP, wireless access, and gateway/routing duties in one device.",
  },
  {
    id: "m2t2-q13",
    type: "multiple_choice",
    prompt: "In the UC 2 Guide, what has to be enabled via services.msc for network discovery of shared devices to work reliably?",
    options: [
      { id: "a", text: "The Function Discovery Provider Host and Function Discovery Resource Publication services" },
      { id: "b", text: "The Print Spooler service only" },
      { id: "c", text: "Windows Update" },
      { id: "d", text: "No services need to be running" },
    ],
    correctOptionIds: ["a"],
    explanation: "The guide has the learner open services.msc and start the Function Discovery Provider and Function Discovery Resources services.",
  },
  {
    id: "m2t2-q14",
    type: "multiple_choice",
    prompt: "What does a subnet mask define for a given IP address?",
    options: [
      { id: "a", text: "Which portion of the address identifies the network and which identifies the host" },
      { id: "b", text: "The physical MAC address of the device" },
      { id: "c", text: "The Wi-Fi password" },
      { id: "d", text: "The device's manufacturer" },
    ],
    correctOptionIds: ["a"],
    explanation: "A subnet mask splits an IP address into its network and host portions, determining which addresses are considered local.",
  },
  {
    id: "m2t2-q15",
    type: "multiple_choice",
    prompt: "A learner configures NIC settings and the router, but never checks whether other PCs can actually see the shared folder or reach each other. What have they skipped?",
    options: [
      { id: "a", text: "Verifying network visibility and diagnosing/checking for faults" },
      { id: "b", text: "Nothing -- configuration alone satisfies the task" },
      { id: "c", text: "Reinstalling the operating system" },
      { id: "d", text: "Crimping a new cable" },
    ],
    correctOptionIds: ["a"],
    explanation: "Job Sheet 2.2-2 explicitly requires confirming visibility across the network and diagnosing any fault, not just applying settings.",
  },
];

export const module2TaskQuizzes: Record<string, QuizQuestion[]> = {
  "task-1": task1Quiz,
  "task-2": task2Quiz,
};
