import type { QuizQuestion } from "../types";

// Sourced from the 4 real UC1 task sheets (see /modules/uc1) and the module's own activity.ts
// (whose steps were themselves built from those same sheets). Each task gets its own
// 15-question quiz, keyed by taskId -- see module1Tasks in ./tasks.ts for the task list.

const task1Quiz: QuizQuestion[] = [
  {
    id: "m1t1-q1",
    type: "multiple_choice",
    prompt: "Before you even touch a screwdriver, what does Task Sheet 1.1-4 require you to do first?",
    options: [
      { id: "a", text: "Follow OH&S policies and procedures and wear appropriate PPE" },
      { id: "b", text: "Remove the side cover" },
      { id: "c", text: "Unplug the monitor only" },
      { id: "d", text: "Back up the hard drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Safety comes before any hands-on step -- OH&S compliance and PPE are the very first line of the procedure.",
  },
  {
    id: "m1t1-q2",
    type: "multiple_choice",
    prompt: "Why does the procedure have you turn the computer on and confirm it works BEFORE disassembling it?",
    options: [
      { id: "a", text: "So you know any problem found after reassembly wasn't already there beforehand" },
      { id: "b", text: "To charge the battery" },
      { id: "c", text: "It's required by the power supply's warranty" },
      { id: "d", text: "There's no real reason, it's optional" },
    ],
    correctOptionIds: ["a"],
    explanation: "Verifying it boots first establishes a baseline -- if something's wrong after reassembly, you know it was introduced during the job.",
  },
  {
    id: "m1t1-q3",
    type: "true_false",
    prompt: "It's fine to handle RAM and the motherboard without any ESD precautions as long as the computer is unplugged.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "Even with the computer unplugged, static electricity from your own body can damage sensitive components -- ground yourself first.",
  },
  {
    id: "m1t1-q4",
    type: "multiple_choice",
    prompt: "What must you make sure of before starting any of the disassembly steps?",
    options: [
      { id: "a", text: "The computer is turned off" },
      { id: "b", text: "The RAM is removed" },
      { id: "c", text: "The screen is unplugged from the wall" },
      { id: "d", text: "The BIOS is reset" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 1.1-4 is explicit: \"Make sure to turn the computer off before doing the steps below.\"",
  },
  {
    id: "m1t1-q5",
    type: "multiple_choice",
    prompt: "In the standard disassembly order, which of these is removed FIRST, right after the two covers?",
    options: [
      { id: "a", text: "The RAM" },
      { id: "b", text: "The motherboard" },
      { id: "c", text: "The power supply unit" },
      { id: "d", text: "The CPU" },
    ],
    correctOptionIds: ["a"],
    explanation: "This build's order is: covers, then RAM 1 and RAM 2, then the optical drive, then the hard drive, then the graphics card, then the cooler, then the PSU, then the CPU, then the motherboard last.",
  },
  {
    id: "m1t1-q6",
    type: "multiple_choice",
    prompt: "What should you do before unscrewing the power supply unit from the case?",
    options: [
      { id: "a", text: "Disconnect its cables from every component it powers" },
      { id: "b", text: "Remove the RAM first" },
      { id: "c", text: "Nothing -- just unscrew it" },
      { id: "d", text: "Reformat the hard drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Disconnecting every power cable first avoids tugging on live connections still attached to other components.",
  },
  {
    id: "m1t1-q7",
    type: "image_identification",
    prompt: "This is the drive you're about to remove from its bay. What should be disconnected before unscrewing it?",
    model3d: { url: "/models/ssd.glb" },
    options: [
      { id: "a", text: "Its data and power cables" },
      { id: "b", text: "The RAM" },
      { id: "c", text: "The CPU fan" },
      { id: "d", text: "The side cover only" },
    ],
    correctOptionIds: ["a"],
    explanation: "Both the data cable (e.g. SATA) and the power cable need to come off before the drive is physically freed from its bay.",
  },
  {
    id: "m1t1-q8",
    type: "multiple_choice",
    prompt: "How do you correctly remove a RAM stick from a DIMM slot?",
    options: [
      { id: "a", text: "Unclip the levers on the sides of the slot, then lift the stick straight out" },
      { id: "b", text: "Pull it out sideways while it's still clipped in" },
      { id: "c", text: "Unscrew it from the slot" },
      { id: "d", text: "Twist it 90 degrees and pull" },
    ],
    correctOptionIds: ["a"],
    explanation: "RAM is held by clips at each end of the slot; unclipping both releases the stick to lift straight out.",
  },
  {
    id: "m1t1-q9",
    type: "image_identification",
    prompt: "This is the motherboard. Why is it removed LAST during disassembly, not earlier?",
    model3d: { url: "/models/motherboard.glb" },
    options: [
      { id: "a", text: "It connects to nearly every other component, so those need to be clear first" },
      { id: "b", text: "It's the lightest part" },
      { id: "c", text: "The manual requires alphabetical order" },
      { id: "d", text: "There's no particular reason" },
    ],
    correctOptionIds: ["a"],
    explanation: "With the drives, RAM, and PSU already out of the way, the motherboard is the one thing left holding everything together.",
  },
  {
    id: "m1t1-q16",
    type: "image_identification",
    prompt: "This is the graphics card you're about to remove. Why does it come off before the motherboard itself?",
    model3d: { url: "/models/gpu.glb" },
    options: [
      { id: "a", text: "It's plugged into the motherboard's PCIe slot, so pulling the board first would leave it dangling loose" },
      { id: "b", text: "It's the heaviest part in the case" },
      { id: "c", text: "The manual requires alphabetical order" },
      { id: "d", text: "There's no particular reason" },
    ],
    correctOptionIds: ["a"],
    explanation: "Like every other part still attached to the board, the graphics card comes off before the board itself is pulled free.",
  },
  {
    id: "m1t1-q17",
    type: "image_identification",
    prompt: "This is the CPU cooler (heatsink) you're about to remove. Why must it come off BEFORE the CPU, not after?",
    model3d: { url: "/models/cooler.glb" },
    options: [
      { id: "a", text: "Its mounting bracket clamps down over the CPU socket, so the CPU can't be freed until the cooler and bracket are off" },
      { id: "b", text: "The cooler is glued permanently to the case" },
      { id: "c", text: "Order doesn't matter between the two" },
      { id: "d", text: "The cooler must stay attached to the CPU at all times" },
    ],
    correctOptionIds: ["a"],
    explanation: "The cooler's bracket physically covers the socket's retention lever -- it has to come off first before the CPU can be released.",
  },
  {
    id: "m1t1-q18",
    type: "multiple_choice",
    prompt: "In this build's disassembly order, which of these is removed LAST, right before the motherboard itself?",
    options: [
      { id: "a", text: "The CPU" },
      { id: "b", text: "The graphics card" },
      { id: "c", text: "The RAM" },
      { id: "d", text: "The front cover" },
    ],
    correctOptionIds: ["a"],
    explanation: "The graphics card, cooler, and RAM all come off the board first -- the CPU is the very last thing pulled before the bare motherboard itself.",
  },
  {
    id: "m1t1-q10",
    type: "multiple_choice",
    prompt: "Which component is installed FIRST when assembling a computer?",
    options: [
      { id: "a", text: "The motherboard" },
      { id: "b", text: "The side cover" },
      { id: "c", text: "The power supply" },
      { id: "d", text: "The RAM" },
    ],
    correctOptionIds: ["a"],
    explanation: "The motherboard goes in first, since nearly everything else attaches to it or is routed around it.",
  },
  {
    id: "m1t1-q11",
    type: "true_false",
    prompt: "The task sheet says motherboard screws should be tightened as hard as possible to make sure it's secure.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "The task sheet's own criteria checklist asks \"were the screws not too tight?\" -- overtightening can crack the board.",
  },
  {
    id: "m1t1-q12",
    type: "image_identification",
    prompt: "This is the RAM module you're about to reinstall. What's the correct way to seat it in its slot?",
    model3d: { url: "/models/ram.glb" },
    options: [
      { id: "a", text: "Line up its notch with the slot's key and press evenly until the side clips snap closed on their own" },
      { id: "b", text: "Force it in at an angle, then straighten it afterward" },
      { id: "c", text: "Screw it directly into the slot" },
      { id: "d", text: "Any orientation works as long as it physically fits" },
    ],
    correctOptionIds: ["a"],
    explanation: "RAM has a notch that only lines up one way -- pressing evenly lets the slot's clips do the locking for you.",
  },
  {
    id: "m1t1-q13",
    type: "image_identification",
    prompt: "This is the power supply unit you just reattached to the case. What must you double-check about it before closing the case up?",
    model3d: { url: "/models/psu.glb" },
    options: [
      { id: "a", text: "That its power cables are connected correctly to the motherboard and drives" },
      { id: "b", text: "That it's painted the right color" },
      { id: "c", text: "That its fan is removed" },
      { id: "d", text: "Nothing further is needed once it's screwed in" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet's criteria explicitly call out making sure the power cables are connected correctly -- a loose connector here means nothing powers on.",
  },
  {
    id: "m1t1-q14",
    type: "image_identification",
    prompt: "This is the front cover you're about to reattach. What's the last physical step before the machine is closed up and powered on again?",
    model3d: { url: "/models/case-side-armour.glb" },
    options: [
      { id: "a", text: "Attaching the front cover and screwing it back on" },
      { id: "b", text: "Attaching the RAM" },
      { id: "c", text: "Attaching the motherboard" },
      { id: "d", text: "Installing the operating system" },
    ],
    correctOptionIds: ["a"],
    explanation: "The solid back cover goes on first, then the outer glass front cover goes back on last.",
  },
  {
    id: "m1t1-q15",
    type: "multiple_choice",
    prompt: "What's the real test that a computer was assembled correctly?",
    options: [
      { id: "a", text: "It boots successfully when turned back on" },
      { id: "b", text: "It looks clean on the outside" },
      { id: "c", text: "All screws are the same size" },
      { id: "d", text: "The side cover closes easily" },
    ],
    correctOptionIds: ["a"],
    explanation: "A successful boot after reassembly is the one thing that actually confirms every connection was made correctly.",
  },
];

const task2Quiz: QuizQuestion[] = [
  {
    id: "m1t2-q1",
    type: "multiple_choice",
    prompt: "What is a bootable USB drive used for?",
    options: [
      { id: "a", text: "Booting a computer and running an installer, such as for an OS" },
      { id: "b", text: "Only storing personal photos" },
      { id: "c", text: "Charging a phone" },
      { id: "d", text: "Replacing the need for a hard drive permanently" },
    ],
    correctOptionIds: ["a"],
    explanation: "A bootable USB drive lets a computer start from it and run an installer, most commonly to install an operating system.",
  },
  {
    id: "m1t2-q2",
    type: "multiple_choice",
    prompt: "Task Sheet 1.2-2 has you use Rufus. What does Rufus actually do?",
    options: [
      { id: "a", text: "Writes an OS installer image onto a USB drive so a computer can boot and install from it" },
      { id: "b", text: "Scans a computer for viruses" },
      { id: "c", text: "Partitions a hard disk drive" },
      { id: "d", text: "Installs device drivers automatically" },
    ],
    correctOptionIds: ["a"],
    explanation: "Rufus is a bootable-media tool -- it takes an installer image (like a Windows ISO) and writes it to the USB drive in a bootable form.",
  },
  {
    id: "m1t2-q3",
    type: "true_false",
    prompt: "Creating a bootable USB drive erases whatever data was already on it.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "Bootable-media tools like Rufus format the drive as part of writing the image -- any existing data on it is lost, so back it up first.",
  },
  {
    id: "m1t2-q4",
    type: "multiple_choice",
    prompt: "What must you follow, besides the on-screen instructions, when creating a bootable flash drive per Task Sheet 1.2-2?",
    options: [
      { id: "a", text: "The software's end-user license agreement" },
      { id: "b", text: "The computer's warranty card" },
      { id: "c", text: "The RAM's manufacturer manual" },
      { id: "d", text: "Nothing else is required" },
    ],
    correctOptionIds: ["a"],
    explanation: "The performance objective is explicit: create the drive \"in accordance with software user guide and software license.\"",
  },
  {
    id: "m1t2-q5",
    type: "multiple_choice",
    prompt: "After creating the bootable device, what's the final required step?",
    options: [
      { id: "a", text: "Test that the created bootable device actually works" },
      { id: "b", text: "Delete the ISO file immediately" },
      { id: "c", text: "Reformat it again" },
      { id: "d", text: "Nothing -- creation alone is sufficient" },
    ],
    correctOptionIds: ["a"],
    explanation: "A bootable drive that hasn't been tested is an assumption, not a confirmed working tool -- the task sheet requires testing it.",
  },
  {
    id: "m1t2-q6",
    type: "true_false",
    prompt: "For a system that boots in UEFI mode, the USB drive generally needs to be formatted FAT32 rather than NTFS to be recognized as bootable.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "Most UEFI firmware only reads FAT32 boot partitions by default, which is why tools like Rufus default to FAT32 for UEFI targets.",
  },
  {
    id: "m1t2-q7",
    type: "multiple_choice",
    prompt: "Why would a freshly created bootable USB fail to boot on some machines even though it was written correctly?",
    options: [
      { id: "a", text: "The computer's boot order/boot device priority isn't set to boot from USB first" },
      { id: "b", text: "USB drives can never be bootable" },
      { id: "c", text: "Bootable drives only work with laptops" },
      { id: "d", text: "The OS installer never needs a bootable drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Even a correctly written bootable USB won't be used if the BIOS/UEFI boot order still prioritizes the internal drive.",
  },
  {
    id: "m1t2-q8",
    type: "multiple_choice",
    prompt: "What's needed as an input before Rufus can create a bootable drive?",
    options: [
      { id: "a", text: "An OS installer image (e.g. a downloaded ISO file)" },
      { id: "b", text: "A working printer" },
      { id: "c", text: "An internet connection at all times" },
      { id: "d", text: "A second hard drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Rufus needs a source image to write -- typically an ISO of the operating system you intend to install.",
  },
  {
    id: "m1t2-q9",
    type: "multiple_choice",
    prompt: "Besides an OS installer, what else might a technician write to a bootable/portable device per this task's materials list?",
    options: [
      { id: "a", text: "Device driver or application installers" },
      { id: "b", text: "Printed manuals only" },
      { id: "c", text: "Nothing else -- only OS images are ever written" },
      { id: "d", text: "Physical screws" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 1.2-2 lists \"device drivers, operating system\" and \"appropriate software application programs\" among its supplies.",
  },
  {
    id: "m1t2-q10",
    type: "true_false",
    prompt: "A bootable USB drive is only useful for installing a fresh operating system -- it can't be used for anything else.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "Bootable drives also carry diagnostic software/utilities and driver or application installers, per the task sheet's own materials list.",
  },
  {
    id: "m1t2-q11",
    type: "multiple_choice",
    prompt: "What's the risk of skipping the \"test the created bootable device\" step before relying on it for a real OS install job?",
    options: [
      { id: "a", text: "You might discover mid-install, on the actual job, that the drive doesn't boot at all" },
      { id: "b", text: "There is no risk" },
      { id: "c", text: "It voids the computer's warranty" },
      { id: "d", text: "It automatically corrupts the hard drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Testing catches a bad write (or a bad USB port/drive) before you're depending on it in front of a client.",
  },
  {
    id: "m1t2-q12",
    type: "multiple_choice",
    prompt: "What does GPT vs. MBR describe when Rufus asks about partition scheme?",
    options: [
      { id: "a", text: "How the target computer's firmware (UEFI vs. legacy BIOS) expects the boot drive to be partitioned" },
      { id: "b", text: "The brand of the USB drive" },
      { id: "c", text: "The file system used for personal documents" },
      { id: "d", text: "The antivirus setting used during install" },
    ],
    correctOptionIds: ["a"],
    explanation: "GPT generally pairs with UEFI systems and MBR with legacy BIOS systems -- picking the wrong one is a common reason a drive won't boot.",
  },
  {
    id: "m1t2-q13",
    type: "multiple_choice",
    prompt: "Why does Task Sheet 1.2-2 start with \"turn the computer on\" before opening Rufus?",
    options: [
      { id: "a", text: "You need a working computer to run Rufus and write the drive in the first place" },
      { id: "b", text: "It's a leftover step with no purpose here" },
      { id: "c", text: "Rufus only runs while the screen is off" },
      { id: "d", text: "It charges the USB drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "Rufus is software that runs on a working computer -- that computer has to be on before you can use it to build the bootable drive.",
  },
  {
    id: "m1t2-q14",
    type: "multiple_choice",
    prompt: "What assessment methods does Task Sheet 1.2-2 use to check this competency?",
    options: [
      { id: "a", text: "Demonstration and oral questioning" },
      { id: "b", text: "A written multiple-choice exam only" },
      { id: "c", text: "A timed typing test" },
      { id: "d", text: "No assessment is specified" },
    ],
    correctOptionIds: ["a"],
    explanation: "Like the other UC1 task sheets, this one is assessed by demonstration with oral questioning, not a written exam.",
  },
  {
    id: "m1t2-q15",
    type: "multiple_choice",
    prompt: "A learner writes a Windows ISO to a USB drive but never boots any machine from it before the graded demonstration. What's missing?",
    options: [
      { id: "a", text: "The required \"test the created bootable device\" step" },
      { id: "b", text: "Nothing -- writing the image alone satisfies the task" },
      { id: "c", text: "A second USB drive as backup" },
      { id: "d", text: "Printing the ISO's file list" },
    ],
    correctOptionIds: ["a"],
    explanation: "The performance criteria checklist requires actually testing that the device works, not just creating it.",
  },
];

const task3Quiz: QuizQuestion[] = [
  {
    id: "m1t3-q1",
    type: "multiple_choice",
    prompt: "Per Task Sheet 1.3-2, what governs how the OS should be installed?",
    options: [
      { id: "a", text: "The established installation procedure" },
      { id: "b", text: "Whatever order feels fastest" },
      { id: "c", text: "The RAM's manufacturer manual" },
      { id: "d", text: "There's no procedure to follow" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet requires the OS to be installed \"in accordance with established installation procedure.\"",
  },
  {
    id: "m1t3-q2",
    type: "multiple_choice",
    prompt: "How many partitions does the task sheet require you to create on the hard disk drive, at minimum?",
    options: [
      { id: "a", text: "At least two" },
      { id: "b", text: "Exactly one" },
      { id: "c", text: "Four" },
      { id: "d", text: "None -- partitioning is optional" },
    ],
    correctOptionIds: ["a"],
    explanation: "\"Create at least two partition of your hard disk drive\" is one of the task sheet's explicit steps.",
  },
  {
    id: "m1t3-q3",
    type: "multiple_choice",
    prompt: "Why create at least two partitions on a hard disk during OS installation?",
    options: [
      { id: "a", text: "Separating the OS from personal files makes future reinstalls and backups safer" },
      { id: "b", text: "It's required by every USB flash drive" },
      { id: "c", text: "It makes the disk physically larger" },
      { id: "d", text: "It has no real benefit" },
    ],
    correctOptionIds: ["a"],
    explanation: "If the OS partition ever needs reinstalling, a separate data partition means personal files aren't at risk.",
  },
  {
    id: "m1t3-q4",
    type: "multiple_choice",
    prompt: "What is a device driver?",
    options: [
      { id: "a", text: "Software that lets the OS communicate with a specific piece of hardware" },
      { id: "b", text: "A physical cable" },
      { id: "c", text: "An antivirus program" },
      { id: "d", text: "A type of partition" },
    ],
    correctOptionIds: ["a"],
    explanation: "Drivers translate between the operating system and hardware -- without the right one, a device may not work at all.",
  },
  {
    id: "m1t3-q5",
    type: "multiple_choice",
    prompt: "The task sheet's last step is \"install missing device drivers.\" Why would drivers be missing right after an OS install?",
    options: [
      { id: "a", text: "A fresh OS install rarely includes every driver a specific machine's hardware needs" },
      { id: "b", text: "OS installers never include any drivers" },
      { id: "c", text: "Drivers are installed automatically by the power supply" },
      { id: "d", text: "Missing drivers is impossible after an OS install" },
    ],
    correctOptionIds: ["a"],
    explanation: "The OS ships generic drivers for common hardware, but specific chipsets, GPUs, or peripherals often still need their own.",
  },
  {
    id: "m1t3-q6",
    type: "multiple_choice",
    prompt: "Where should a technician get the correct driver for a specific piece of hardware?",
    options: [
      { id: "a", text: "The manufacturer's driver download or the hardware's included manual/media" },
      { id: "b", text: "Any random driver with a similar name" },
      { id: "c", text: "It doesn't matter which driver is installed" },
      { id: "d", text: "Drivers can't be obtained separately from the OS" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 1.3-2 lists \"hardware manuals\" among its supplies precisely because the right driver comes from the hardware's manufacturer.",
  },
  {
    id: "m1t3-q7",
    type: "true_false",
    prompt: "Software license agreements only matter for the operating system, not for individual drivers or applications installed afterward.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "Every piece of software -- OS, drivers, and applications alike -- comes with its own license agreement that should be followed.",
  },
  {
    id: "m1t3-q8",
    type: "multiple_choice",
    prompt: "In Windows, how can a technician confirm whether a device is still missing its proper driver?",
    options: [
      { id: "a", text: "Check Device Manager for a device flagged with a warning icon or listed as \"Unknown device\"" },
      { id: "b", text: "Check the case's side cover" },
      { id: "c", text: "Run a disk defragmenter" },
      { id: "d", text: "There's no way to check" },
    ],
    correctOptionIds: ["a"],
    explanation: "Device Manager flags hardware that's missing a proper driver, which is the standard way to spot the problem.",
  },
  {
    id: "m1t3-q9",
    type: "multiple_choice",
    prompt: "What has to happen before you can begin installing the operating system, based on the previous task?",
    options: [
      { id: "a", text: "A tested, working bootable device (USB) with the OS installer needs to exist" },
      { id: "b", text: "The antivirus must already be installed" },
      { id: "c", text: "The office suite must already be installed" },
      { id: "d", text: "Nothing -- OS install requires no preparation" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task 1.3-2 follows directly from Task 1.2-2's bootable device -- you boot from that USB to start the OS install.",
  },
  {
    id: "m1t3-q10",
    type: "multiple_choice",
    prompt: "What are the two required task-sheet supplies for installing an OS and its drivers?",
    options: [
      { id: "a", text: "The OS installer and device driver installers" },
      { id: "b", text: "A crimping tool and a LAN tester" },
      { id: "c", text: "A screwdriver and a flashlight" },
      { id: "d", text: "An antivirus license and a browser installer" },
    ],
    correctOptionIds: ["a"],
    explanation: "Task Sheet 1.3-2 lists the OS installer and device driver installers alongside hardware manuals and software licenses.",
  },
  {
    id: "m1t3-q11",
    type: "multiple_choice",
    prompt: "A learner installs Windows but skips creating a second partition. What criterion have they failed?",
    options: [
      { id: "a", text: "\"Create at least two partition of your hard disk drive\"" },
      { id: "b", text: "\"Install missing device drivers\"" },
      { id: "c", text: "\"Perform Operating System installation\"" },
      { id: "d", text: "None -- one partition is always acceptable" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet's own performance criteria checklist requires at least two partitions be created.",
  },
  {
    id: "m1t3-q12",
    type: "multiple_choice",
    prompt: "Why does installing drivers usually come AFTER installing the OS rather than before?",
    options: [
      { id: "a", text: "Drivers are software that runs on top of the OS, so the OS has to exist first" },
      { id: "b", text: "Drivers physically attach to the motherboard" },
      { id: "c", text: "There's no required order" },
      { id: "d", text: "Drivers replace the need for an OS" },
    ],
    correctOptionIds: ["a"],
    explanation: "A driver is OS-level software that lets that OS talk to a piece of hardware -- it needs an installed OS to run on.",
  },
  {
    id: "m1t3-q13",
    type: "true_false",
    prompt: "Once the OS is installed, hardware manuals become useless and can be discarded.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "Hardware manuals remain the reference for correct driver installation and configuration even after the OS is up and running.",
  },
  {
    id: "m1t3-q14",
    type: "multiple_choice",
    prompt: "What assessment methods are used to check this OS/drivers competency, per the task sheet?",
    options: [
      { id: "a", text: "Demonstration and oral questioning" },
      { id: "b", text: "A written essay only" },
      { id: "c", text: "A group project" },
      { id: "d", text: "No assessment is specified" },
    ],
    correctOptionIds: ["a"],
    explanation: "Like the other UC1 task sheets, this one is assessed by demonstration with oral questioning.",
  },
  {
    id: "m1t3-q15",
    type: "multiple_choice",
    prompt: "What's the correct high-level order for this task's three required steps?",
    options: [
      { id: "a", text: "Install the OS, create partitions, then install missing drivers" },
      { id: "b", text: "Install drivers, then install the OS" },
      { id: "c", text: "Create partitions, install drivers, then install the OS" },
      { id: "d", text: "Order doesn't matter at all" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet lists the steps in this order: perform the OS installation (which includes partitioning), then install missing drivers.",
  },
];

const task4Quiz: QuizQuestion[] = [
  {
    id: "m1t4-q1",
    type: "multiple_choice",
    prompt: "Per Task Sheet 1.3-3, what three things must guide application software installation?",
    options: [
      { id: "a", text: "Software installation guides, end-user requirements, and the software license agreement" },
      { id: "b", text: "Only the installer's file size" },
      { id: "c", text: "Only what's fastest to install" },
      { id: "d", text: "Nothing -- any install method is acceptable" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet's performance objective names all three: installation guides, end-user requirements, and the license agreement.",
  },
  {
    id: "m1t4-q2",
    type: "multiple_choice",
    prompt: "Which web browser does the task sheet specifically name as an example to install?",
    options: [
      { id: "a", text: "Google Chrome" },
      { id: "b", text: "Internet Explorer" },
      { id: "c", text: "Opera" },
      { id: "d", text: "Safari" },
    ],
    correctOptionIds: ["a"],
    explanation: "\"Install Google Chrome\" is listed directly as one of the task sheet's required steps.",
  },
  {
    id: "m1t4-q3",
    type: "multiple_choice",
    prompt: "Which office application suite does the task sheet name as an example to install?",
    options: [
      { id: "a", text: "MS Office" },
      { id: "b", text: "LibreOffice" },
      { id: "c", text: "Google Docs" },
      { id: "d", text: "WordPerfect" },
    ],
    correctOptionIds: ["a"],
    explanation: "\"Install MS Office Application\" is one of the task sheet's named steps.",
  },
  {
    id: "m1t4-q4",
    type: "multiple_choice",
    prompt: "What does the task sheet say about installing antivirus software?",
    options: [
      { id: "a", text: "Install it if required" },
      { id: "b", text: "It must never be installed" },
      { id: "c", text: "It replaces the need for an operating system" },
      { id: "d", text: "It must be installed before the OS" },
    ],
    correctOptionIds: ["a"],
    explanation: "The step is worded \"Install Antivirus (if any),\" meaning it applies when the end-user setup calls for it.",
  },
  {
    id: "m1t4-q5",
    type: "multiple_choice",
    prompt: "What is an end-user license agreement (EULA)?",
    options: [
      { id: "a", text: "The terms a user must accept to legally install and use a piece of software" },
      { id: "b", text: "A warranty card for hardware" },
      { id: "c", text: "A type of driver" },
      { id: "d", text: "A backup schedule" },
    ],
    correctOptionIds: ["a"],
    explanation: "A EULA sets the legal terms of use between the software publisher and the person installing it.",
  },
  {
    id: "m1t4-q6",
    type: "multiple_choice",
    prompt: "Antivirus software is typically installed early, before general browsing begins. Why?",
    options: [
      { id: "a", text: "It protects the freshly installed system before it's exposed to untrusted files or networks" },
      { id: "b", text: "It has to be installed before Windows itself" },
      { id: "c", text: "It permanently disables the browser" },
      { id: "d", text: "There's no benefit to installing it early" },
    ],
    correctOptionIds: ["a"],
    explanation: "A brand-new system is most vulnerable in the window before protection is in place -- installing antivirus early closes that gap.",
  },
  {
    id: "m1t4-q7",
    type: "true_false",
    prompt: "\"End-user requirements\" means installing every possible application whether or not the user actually needs it.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["false"],
    explanation: "Installing based on end-user requirements means installing what that specific user actually needs, not everything available.",
  },
  {
    id: "m1t4-q8",
    type: "multiple_choice",
    prompt: "Why is ignoring a software's license agreement a real risk for a technician, not just a formality?",
    options: [
      { id: "a", text: "It can mean the software is being used or distributed illegally" },
      { id: "b", text: "License agreements have no real consequence" },
      { id: "c", text: "It only affects the software's color scheme" },
      { id: "d", text: "It automatically uninstalls the software" },
    ],
    correctOptionIds: ["a"],
    explanation: "License terms are legally binding -- violating them (e.g. installing beyond the licensed number of seats) is a real compliance risk.",
  },
  {
    id: "m1t4-q9",
    type: "multiple_choice",
    prompt: "After installing an application, what's the simplest way to confirm the installation actually succeeded?",
    options: [
      { id: "a", text: "Launch it and confirm it opens and works" },
      { id: "b", text: "Assume it worked if the installer closed" },
      { id: "c", text: "Check the RAM amount" },
      { id: "d", text: "Reboot into the bootable USB drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "An installer finishing without error is a good sign, but actually opening the application is the real confirmation it works.",
  },
  {
    id: "m1t4-q10",
    type: "multiple_choice",
    prompt: "A learner installs an office suite but never checks whether the end user actually wanted it, or reads its license terms. What have they skipped?",
    options: [
      { id: "a", text: "Installing based on end-user requirements and the software license agreement" },
      { id: "b", text: "Nothing -- installing any software satisfies the task" },
      { id: "c", text: "Creating a hard disk partition" },
      { id: "d", text: "Installing a device driver" },
    ],
    correctOptionIds: ["a"],
    explanation: "The task sheet's performance objective requires installing per end-user requirements and the license agreement, not just per install guide.",
  },
  {
    id: "m1t4-q11",
    type: "multiple_choice",
    prompt: "What's a practical reason to keep track of an installed application's license key or proof of purchase?",
    options: [
      { id: "a", text: "It may be needed to reinstall, transfer, or reactivate the software later" },
      { id: "b", text: "License keys expire after one use and are otherwise worthless" },
      { id: "c", text: "It has no ongoing use once installed" },
      { id: "d", text: "It's only needed for antivirus software" },
    ],
    correctOptionIds: ["a"],
    explanation: "Reinstalling on the same machine, or after a repair, often requires the original license key again.",
  },
  {
    id: "m1t4-q12",
    type: "multiple_choice",
    prompt: "What's the main difference between an operating system, a device driver, and an application, in terms of their role?",
    options: [
      { id: "a", text: "The OS manages the whole machine, a driver lets the OS talk to specific hardware, and an application does a task for the end user" },
      { id: "b", text: "They're all exactly the same kind of software" },
      { id: "c", text: "A driver is a type of application software" },
      { id: "d", text: "An OS is a type of application" },
    ],
    correctOptionIds: ["a"],
    explanation: "Each sits at a different layer: OS (whole system) → driver (hardware-specific) → application (a user-facing task).",
  },
  {
    id: "m1t4-q13",
    type: "true_false",
    prompt: "Software installation guides exist to help ensure an application is installed the way its publisher intended.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "Following the installation guide reduces the chance of misconfiguration or a broken install.",
  },
  {
    id: "m1t4-q14",
    type: "multiple_choice",
    prompt: "What assessment methods does Task Sheet 1.3-3 use?",
    options: [
      { id: "a", text: "Demonstration and oral questioning" },
      { id: "b", text: "A closed-book written exam only" },
      { id: "c", text: "Peer review only" },
      { id: "d", text: "No assessment is specified" },
    ],
    correctOptionIds: ["a"],
    explanation: "Consistent with the other UC1 task sheets, this one is assessed by demonstration with oral questioning.",
  },
  {
    id: "m1t4-q15",
    type: "multiple_choice",
    prompt: "This is the last task in Module 1's build-a-computer flow. What has the technician accomplished by the end of it?",
    options: [
      { id: "a", text: "A disassembled-and-reassembled machine, running an installed OS with drivers, a browser, an office suite, and antivirus" },
      { id: "b", text: "Only a working browser installation" },
      { id: "c", text: "Only physical hardware assembly, with no software installed" },
      { id: "d", text: "A bootable USB drive with nothing else done" },
    ],
    correctOptionIds: ["a"],
    explanation: "Module 1's four tasks form one start-to-finish flow: rebuild the hardware, create bootable media, install the OS and drivers, then install applications.",
  },
];

export const module1TaskQuizzes: Record<string, QuizQuestion[]> = {
  "task-1": task1Quiz,
  "task-2": task2Quiz,
  "task-3": task3Quiz,
  "task-4": task4Quiz,
};
