import type { QuizQuestion } from "../types";

// Sourced from the UC3 Guide and Job Sheets 3.1-2 "Setting-Up User Access" and 3.2-2
// "Configuring Network Services" (see /modules/uc3), including the guide's own worked example
// (root domain css.org, network ID 10.10.0, OU named "Redirection"). Each task gets its own
// 15-question quiz, keyed by taskId.

const task1Quiz: QuizQuestion[] = [
  {
    id: "m3t1-q1",
    type: "multiple_choice",
    prompt: "What must be true about the server's IP address before you start configuring its roles?",
    options: [
      { id: "a", text: "It must be static, not dynamically assigned" },
      { id: "b", text: "It must be on a different subnet than every client" },
      { id: "c", text: "It doesn't matter -- any IP works" },
      { id: "d", text: "It must be IPv6 only" },
    ],
    correctOptionIds: ["a"],
    explanation: "The UC3 Guide starts with \"make sure that the server's IP address is static\" -- clients need to be able to find the server reliably.",
  },
  {
    id: "m3t1-q2",
    type: "multiple_choice",
    prompt: "What does the Active Directory Domain Services (AD DS) role provide?",
    options: [
      { id: "a", text: "A central directory of users, computers, and policies for the network" },
      { id: "b", text: "Automatic IP address assignment" },
      { id: "c", text: "Name-to-IP resolution" },
      { id: "d", text: "Printer sharing only" },
    ],
    correctOptionIds: ["a"],
    explanation: "AD DS is what turns a plain server into a domain controller -- the central store of accounts and policy for the network.",
  },
  {
    id: "m3t1-q3",
    type: "multiple_choice",
    prompt: "Which four roles does Job Sheet 3.1-2 have you add to the server?",
    options: [
      { id: "a", text: "ADDS, DNS, DHCP, and Print Management Services" },
      { id: "b", text: "Only a web server role" },
      { id: "c", text: "Only antivirus" },
      { id: "d", text: "Only a backup service" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's step is explicit: \"Add the following roles and services. ADDS, DNS, DHCP, and Print Management Services.\"",
  },
  {
    id: "m3t1-q4",
    type: "multiple_choice",
    prompt: "What happens when you \"promote\" a server to a domain controller?",
    options: [
      { id: "a", text: "It creates (or joins) a domain that client machines can then be joined to" },
      { id: "b", text: "It converts the server into a client PC" },
      { id: "c", text: "It deletes all existing user accounts" },
      { id: "d", text: "It disables DHCP permanently" },
    ],
    correctOptionIds: ["a"],
    explanation: "The UC3 Guide has you \"Add a New Forest\" with a root domain name (e.g. css.org) as part of promoting the server.",
  },
  {
    id: "m3t1-q5",
    type: "multiple_choice",
    prompt: "In the UC3 Guide's worked example, what's used as the root domain name?",
    options: [
      { id: "a", text: "css.org" },
      { id: "b", text: "example.com" },
      { id: "c", text: "localhost" },
      { id: "d", text: "It's left blank" },
    ],
    correctOptionIds: ["a"],
    explanation: "The guide's promotion step types css.org as the root domain name when adding a new forest.",
  },
  {
    id: "m3t1-q6",
    type: "multiple_choice",
    prompt: "What's the purpose of a DNS reverse lookup zone, which this task has you set up?",
    options: [
      { id: "a", text: "Resolving an IP address back to a hostname (the opposite of a normal forward lookup)" },
      { id: "b", text: "Assigning IP addresses automatically" },
      { id: "c", text: "Sharing folders across the network" },
      { id: "d", text: "Managing printer drivers" },
    ],
    correctOptionIds: ["a"],
    explanation: "A forward zone resolves names to IPs; a reverse lookup zone does the opposite, resolving an IP back to a name.",
  },
  {
    id: "m3t1-q7",
    type: "true_false",
    prompt: "Completing the DHCP configuration on a newly promoted domain controller requires authorizing the DHCP server.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "The DHCP Post-Install Configuration Wizard's Authorization screen authorizes the DHCP server under domain administrator credentials before it can hand out leases.",
  },
  {
    id: "m3t1-q8",
    type: "multiple_choice",
    prompt: "What's an Organizational Unit (OU) used for in Active Directory?",
    options: [
      { id: "a", text: "Grouping related accounts/objects together so policies can be applied to all of them at once" },
      { id: "b", text: "Storing backup files" },
      { id: "c", text: "Assigning static IP addresses" },
      { id: "d", text: "Formatting hard drives" },
    ],
    correctOptionIds: ["a"],
    explanation: "An OU is a container for users/computers that Group Policy Objects can be linked to, applying settings to everyone inside it at once.",
  },
  {
    id: "m3t1-q9",
    type: "multiple_choice",
    prompt: "How many user accounts does Job Sheet 3.1-2 have you create under the new Organizational Unit?",
    options: [
      { id: "a", text: "Two" },
      { id: "b", text: "One" },
      { id: "c", text: "Five" },
      { id: "d", text: "Zero -- no users are created" },
    ],
    correctOptionIds: ["a"],
    explanation: "\"Create a new Organizational unit and create two users\" is one of the job sheet's explicit steps.",
  },
  {
    id: "m3t1-q10",
    type: "multiple_choice",
    prompt: "What permission level does the job sheet have you grant \"Everyone\" on the shared UserFiles folder?",
    options: [
      { id: "a", text: "Read/Write" },
      { id: "b", text: "Read only" },
      { id: "c", text: "No access" },
      { id: "d", text: "Write only, no read" },
    ],
    correctOptionIds: ["a"],
    explanation: "The step says to \"add make sure everyone has a read/write permission\" to the UserFiles folder.",
  },
  {
    id: "m3t1-q11",
    type: "multiple_choice",
    prompt: "What is a Group Policy Object (GPO) used for?",
    options: [
      { id: "a", text: "Applying a set of configuration settings automatically to every account/computer in a linked OU" },
      { id: "b", text: "Encrypting a single user's files" },
      { id: "c", text: "Assigning printer IP addresses" },
      { id: "d", text: "Creating new hard disk partitions" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet has you create a GPO inside the Organizational Unit, which then applies its settings (like folder redirection) to that whole OU.",
  },
  {
    id: "m3t1-q12",
    type: "multiple_choice",
    prompt: "Which three folders does this task's folder redirection get configured for?",
    options: [
      { id: "a", text: "Desktop, My Documents, and Pictures" },
      { id: "b", text: "Downloads, Music, and Videos" },
      { id: "c", text: "Only Desktop" },
      { id: "d", text: "The entire C: drive" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's step is: \"Configure Folder Redirection Settings on both Desktop, My Documents and pictures.\"",
  },
  {
    id: "m3t1-q13",
    type: "image_identification",
    prompt: "This is the server machine you're configuring in this task. Which of these roles does it end up hosting by the end of the task?",
    model3d: { url: "/models/server-rack.glb" },
    options: [
      { id: "a", text: "Active Directory Domain Services, DNS, and DHCP, as a domain controller" },
      { id: "b", text: "Only a web browser" },
      { id: "c", text: "Only antivirus software" },
      { id: "d", text: "No roles -- it stays a plain client PC" },
    ],
    correctOptionIds: ["a"],
    explanation: "By the end of the task, the server is a domain controller running AD DS, DNS, and DHCP, with user accounts and folder redirection configured.",
  },
  {
    id: "m3t1-q14",
    type: "multiple_choice",
    prompt: "What has to happen on a client PC's network adapter settings before it can join the domain?",
    options: [
      { id: "a", text: "Its preferred DNS server needs to be set to the domain controller's IP address" },
      { id: "b", text: "Its firewall needs to be permanently disabled" },
      { id: "c", text: "It needs a second network card installed" },
      { id: "d", text: "Nothing -- clients can join without any adapter changes" },
    ],
    correctOptionIds: ["a"],
    explanation: "Since the domain controller also runs DNS, the client has to point its DNS at the server's IP address to resolve and find the domain.",
  },
  {
    id: "m3t1-q15",
    type: "multiple_choice",
    prompt: "After a client joins the domain and logs in with a domain account, how do you check that folder redirection actually worked?",
    options: [
      { id: "a", text: "Open the shared UserFiles folder on the server and confirm a folder for that user's Desktop/Documents/Pictures appeared" },
      { id: "b", text: "Check the client's IP address only" },
      { id: "c", text: "Restart the router" },
      { id: "d", text: "There's no way to verify this" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's checklist requires checking that folder redirection works -- the redirected folders should appear under the user's name inside UserFiles.",
  },
];

const task2Quiz: QuizQuestion[] = [
  {
    id: "m3t2-q1",
    type: "multiple_choice",
    prompt: "What must be enabled on the client PC before a Remote Desktop Connection to it will work?",
    options: [
      { id: "a", text: "\"Allow remote connections to this PC\" in its remote settings" },
      { id: "b", text: "A second monitor" },
      { id: "c", text: "A static IP on the router only" },
      { id: "d", text: "Nothing needs to be enabled" },
    ],
    correctOptionIds: ["a"],
    explanation: "Job Sheet 3.2-2 has the client PC go to remote settings and check \"allow remote connection to this PC.\"",
  },
  {
    id: "m3t2-q2",
    type: "multiple_choice",
    prompt: "Besides enabling remote connections, what else does the client-side setup require?",
    options: [
      { id: "a", text: "Adding the user(s) who should have remote access to this PC" },
      { id: "b", text: "Disabling the network adapter" },
      { id: "c", text: "Uninstalling the print driver" },
      { id: "d", text: "Nothing else is required" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's step \"Add user to ensure users will have access to this pc in remote desktop\" grants specific accounts remote access.",
  },
  {
    id: "m3t2-q3",
    type: "multiple_choice",
    prompt: "From where is the Remote Desktop Connection actually initiated, per the job sheet?",
    options: [
      { id: "a", text: "From the Server-PC, connecting out to the Client-PC" },
      { id: "b", text: "From the client, connecting to itself" },
      { id: "c", text: "From the router's admin page" },
      { id: "d", text: "It initiates automatically with no user action" },
    ],
    correctOptionIds: ["a"],
    explanation: "The step is \"Go to Server-PC and run Remote Desktop Connection\" then enter the Client-PC's IP address.",
  },
  {
    id: "m3t2-q4",
    type: "multiple_choice",
    prompt: "What does the technician need to know about the target machine to start a Remote Desktop Connection to it?",
    options: [
      { id: "a", text: "Its IP address" },
      { id: "b", text: "Its case color" },
      { id: "c", text: "Its RAM amount" },
      { id: "d", text: "Nothing -- it connects automatically" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's step is literally \"Enter the Client-PC IP address\" into the Remote Desktop Connection tool.",
  },
  {
    id: "m3t2-q5",
    type: "multiple_choice",
    prompt: "What does the Print and Document Services role, added on the server, enable?",
    options: [
      { id: "a", text: "Installing a network printer once on the server and pushing/deploying it out to clients centrally" },
      { id: "b", text: "Automatic IP address assignment" },
      { id: "c", text: "Remote desktop access" },
      { id: "d", text: "DNS name resolution" },
    ],
    correctOptionIds: ["a"],
    explanation: "Print and Document Services centralizes printer setup so it doesn't need to be repeated by hand on every client.",
  },
  {
    id: "m3t2-q6",
    type: "multiple_choice",
    prompt: "What's the order of steps for the printer-deployment half of this job sheet?",
    options: [
      { id: "a", text: "Add the Print and Document Services role, install the network printer, then deploy it to clients" },
      { id: "b", text: "Deploy the printer to clients before it's even installed on the server" },
      { id: "c", text: "Install the printer directly on every client individually" },
      { id: "d", text: "Uninstall the printer, then reinstall it" },
    ],
    correctOptionIds: ["a"],
    explanation: "The job sheet's steps are: add the role, install the network printer, then deploy the installed printer to clients.",
  },
  {
    id: "m3t2-q7",
    type: "multiple_choice",
    prompt: "How does the job sheet have you confirm the printer deployment actually worked?",
    options: [
      { id: "a", text: "Go to the Client-PC and print a sample document" },
      { id: "b", text: "Check the printer's serial number" },
      { id: "c", text: "Restart the server" },
      { id: "d", text: "Nothing further is checked" },
    ],
    correctOptionIds: ["a"],
    explanation: "The final step is: \"Go to Client-PC and print a sample document,\" proving the deployed printer actually works from the client's side.",
  },
  {
    id: "m3t2-q8",
    type: "true_false",
    prompt: "A key benefit of deploying a printer centrally from the server, rather than installing it on each PC by hand, is consistent driver management across every client.",
    options: [
      { id: "true", text: "True" },
      { id: "false", text: "False" },
    ],
    correctOptionIds: ["true"],
    explanation: "Print and Document Services lets an administrator manage drivers and settings in one place instead of on every machine individually.",
  },
  {
    id: "m3t2-q9",
    type: "multiple_choice",
    prompt: "Why is it important to only add specific, trusted users when enabling Remote Desktop access to a PC?",
    options: [
      { id: "a", text: "Remote Desktop grants full interactive control of that PC -- unrestricted access is a real security risk" },
      { id: "b", text: "It has no security implications at all" },
      { id: "c", text: "Remote Desktop only allows read-only viewing regardless of who's added" },
      { id: "d", text: "Adding more users always makes it more secure" },
    ],
    correctOptionIds: ["a"],
    explanation: "Whoever's allowed to remote in can operate the PC as if sitting in front of it, so access should be limited to people who actually need it.",
  },
  {
    id: "m3t2-q10",
    type: "multiple_choice",
    prompt: "What assessment methods does Job Sheet 3.2-2 specify?",
    options: [
      { id: "a", text: "Demonstration with oral questioning and a performance criteria checklist" },
      { id: "b", text: "A written-only exam" },
      { id: "c", text: "No formal assessment" },
      { id: "d", text: "Peer grading only" },
    ],
    correctOptionIds: ["a"],
    explanation: "Like the other UC3 job sheets, this one is assessed via demonstration with oral questioning and a performance criteria checklist.",
  },
  {
    id: "m3t2-q11",
    type: "multiple_choice",
    prompt: "If Remote Desktop Connection from the server fails to reach the client, what's a likely cause worth checking first?",
    options: [
      { id: "a", text: "\"Allow remote connections\" isn't enabled on the client, or a firewall is blocking it" },
      { id: "b", text: "The printer driver is outdated" },
      { id: "c", text: "The server's RAM is too small" },
      { id: "d", text: "The domain name is too long" },
    ],
    correctOptionIds: ["a"],
    explanation: "The two most common causes of a failed RDP connection are the client not allowing remote connections and a firewall blocking the RDP port.",
  },
  {
    id: "m3t2-q12",
    type: "multiple_choice",
    prompt: "What do both halves of this job sheet (remote desktop and printer deployment) have in common?",
    options: [
      { id: "a", text: "Both let the server centrally manage or reach a client resource over the network" },
      { id: "b", text: "Both require physically opening the computer case" },
      { id: "c", text: "Neither requires any network connectivity" },
      { id: "d", text: "Both are unrelated to Module 3's server setup" },
    ],
    correctOptionIds: ["a"],
    explanation: "Remote Desktop reaches a client's desktop remotely, and printer deployment pushes a resource from the server out to clients -- both are network services running on top of the domain infrastructure set up in Task 1.",
  },
  {
    id: "m3t2-q13",
    type: "multiple_choice",
    prompt: "Job Sheet 3.2-2's checklist requires printer deployment to follow what?",
    options: [
      { id: "a", text: "Enterprise policies and procedures" },
      { id: "b", text: "Only the end user's personal preference" },
      { id: "c", text: "No particular policy" },
      { id: "d", text: "The router's default settings" },
    ],
    correctOptionIds: ["a"],
    explanation: "The checklist item reads: \"Perform printer deployment ... based on enterprise policies and procedures.\"",
  },
  {
    id: "m3t2-q14",
    type: "multiple_choice",
    prompt: "For satisfactory achievement on this job sheet's performance criteria checklist, what response is required on every item?",
    options: [
      { id: "a", text: "A YES response on every item" },
      { id: "b", text: "At least 70% YES responses" },
      { id: "c", text: "Any mix of YES/NO is acceptable" },
      { id: "d", text: "Only the last item needs a YES" },
    ],
    correctOptionIds: ["a"],
    explanation: "Job/task sheets in this program state: \"For satisfactory achievement, all items should receive a YES response.\"",
  },
  {
    id: "m3t2-q15",
    type: "multiple_choice",
    prompt: "By the end of Module 3's two tasks, what has the technician built?",
    options: [
      { id: "a", text: "A domain with user accounts, folder redirection, remote desktop access, and centrally deployed printing" },
      { id: "b", text: "Only a standalone client PC with no server" },
      { id: "c", text: "Only a physical cable installation with no software configuration" },
      { id: "d", text: "A single local user account with no network services" },
    ],
    correctOptionIds: ["a"],
    explanation: "Module 3's two tasks build on each other: first the domain, users, and folder redirection, then the network services (remote desktop, printing) on top of it.",
  },
];

export const module3TaskQuizzes: Record<string, QuizQuestion[]> = {
  "task-1": task1Quiz,
  "task-2": task2Quiz,
};
